.docker-job:
  image: docker:20.10.6
  services:
    - docker:20.10.6-dind
  variables:
    DOCKER_DRIVER: overlay

.docker-build-job:
  extends: .docker-job
  script:
    - mkdir "$IMAGE-$VERSION"
    - docker build -t "$CI_REGISTRY_IMAGE/$IMAGE:$VERSION" -f "$DOCKERFILE" "$CONTEXT"
    - docker save "$CI_REGISTRY_IMAGE/$IMAGE:$VERSION" | gzip > "$IMAGE-$VERSION/image.tar.gz"
  artifacts:
    expire_in: 1 days
    paths:
      - $IMAGE-$VERSION/image.tar.gz

.docker-push-job:
  extends: .docker-job
  before_script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker load < $IMAGE-$VERSION/image.tar.gz
    - |
      for TAG in $PUSH_TAGS
        do
          docker tag $CI_REGISTRY_IMAGE/$IMAGE:$VERSION $CI_REGISTRY_IMAGE/$IMAGE:$TAG
          docker push $CI_REGISTRY_IMAGE/$IMAGE:$TAG
        done

.theia-extension-build-job:
  image: node:14.18-buster-slim
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  cache:
    paths:
      - ./vscode-extensions/$EXTENSION_DIR/node_modules
  script:
    - cd ./vscode-extensions/$EXTENSION_DIR
    - npm install -g vsce --unsafe-perm
    - yarn

test-build-cinco-extension:
  extends: .theia-extension-build-job
  variables:
    EXTENSION_DIR: cinco-extension

test-build-cinco-project-initializer-extension:
  extends: .theia-extension-build-job
  variables:
    EXTENSION_DIR: cinco-project-initializer

test-build-pyro-client-extension:
  extends: .theia-extension-build-job
  variables:
    EXTENSION_DIR: pyro-client-extension

build:
  extends: .docker-build-job
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs:
    - test-build-cinco-extension
    - test-build-cinco-project-initializer-extension
    - test-build-pyro-client-extension
  variables:
    CONTEXT: .
    DOCKERFILE: ./Dockerfile
    IMAGE: archetype
    VERSION: latest
    GIT_SUBMODULE_STRATEGY: recursive

push:
  extends: .docker-push-job
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs:
    - build
  variables:
    IMAGE: archetype
    VERSION: latest
    PUSH_TAGS: latest $CI_COMMIT_SHA

# feature-branch pipeline
build-dev:
  extends: .docker-build-job
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH
  when: manual
  variables:
    CONTEXT: .
    DOCKERFILE: ./Dockerfile
    IMAGE: archetype
    VERSION: dev
    GIT_SUBMODULE_STRATEGY: recursive

push-dev:
  extends: .docker-push-job
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH
  needs:
    - build-dev
  variables:
    IMAGE: archetype
    VERSION: dev
    PUSH_TAGS: dev-$CI_COMMIT_REF_NAME

