version: '3.2'

services:
  wildfly:
    environment:
      CLIENT_ORIGIN: http://127.0.0.1
    restart: on-failure:5
    ports:
      - "127.0.0.1:8081:8080"
  postgres:
    restart: on-failure:5
  angular:
    build:
      context: webapp
    restart: on-failure:5
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - wildfly
