/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.core.ge.style.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.jabc.cinco.meta.core.ge.style.StyleRuntimeModule;
import de.jabc.cinco.meta.core.ge.style.StyleStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StyleIdeSetup extends StyleStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StyleRuntimeModule(), new StyleIdeModule()));
	}
	
}
