/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.core.ge.style.ide;


/**
 * Use this class to register ide components.
 */
public class StyleIdeModule extends AbstractStyleIdeModule {
}
