# build the pyro server
FROM docker.io/google/dart:2.4.1 as pyro-server-frontend-builder
WORKDIR /pyro-server
COPY ./pyro/webapp /pyro-server/webapp
RUN cd webapp \
    && pub global activate webdev \
    && pub get \
    && pub run build_runner build -o build

# --------------------------------
FROM docker.io/library/maven:3-adoptopenjdk-11 as pyro-server-builder
WORKDIR /pyro-server
COPY --from=pyro-server-frontend-builder /pyro-server/webapp/ /pyro-server/webapp/
COPY ./pyro/app /pyro-server/app
COPY ./pyro/compile.sh /pyro-server/compile.sh
# make outsourced compilation-script executable
RUN sed -i 's/\r$//' /pyro-server/compile.sh  && \  
    chmod +x /pyro-server/compile.sh
# outputs pyro-model-server to pyro-server/pyro-server
RUN /pyro-server/compile.sh

# build pyro client
# --------------------------------
#FROM docker.io/library/node:12.14.1-buster-slim as pyro-client-builder
#WORKDIR /pyro-client-extension
#COPY ./pyro-client-extension /pyro-client-extension
# outputs extension to /pyro-client/pyro-client-0.0.1.vsix
#RUN npm install -g vsce
#RUN yarn

# build the theia editor
# --------------------------------
FROM docker.io/library/openjdk:11.0.12-slim-bullseye
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV CINCO_CLOUD_HOST=cinco-cloud
ENV CINCO_CLOUD_PORT=80
ENV CINCO_CLOUD_DEBUG=false
ENV THEIA_WEBVIEW_EXTERNAL_ENDPOINT='{{hostname}}'
ENV PYRO_HOST="localhost"
# make readable for root only
RUN chmod -R 750 /var/run/
WORKDIR /editor
COPY ./editor /editor
RUN useradd -ms /bin/bash theia
COPY --chown=theia:theia web /editor
# install node and yarn
RUN apt update && \
    apt install -y gnupg gnupg2 curl && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt update && \
    apt install -y nodejs npm yarn && \
    apt remove -y gnupg gnupg2 curl && \
    apt install -y libsecret-1-dev && \
    apt autoremove -y

# copy pyro-server to singleton pyro-server-extension
COPY --from=pyro-server-builder /pyro-server/pyro-server/ /editor/pyro-server-extension/pyro-server/

# install theia
# RUN yarn
# copy pyro-client after the build
# COPY --from=pyro-client-builder /pyro-client-extension/pyro-client-extension-0.0.1.vsix /editor/browser-app/plugins

# integrate favicon
RUN sed -i 's/<\/head>/<link rel="icon" href="favicon.ico" \/><\/head>/g' /editor/browser-app/lib/index.html
RUN mkdir /editor/workspace

VOLUME /editor/workspace
EXPOSE 3000 8000
CMD cd /editor/browser-app && \
    # TODO: comment CINCO_CLOUD_DEBUG out, for debug purpose only (insecure)
    DATABASE_URL="${DATABASE_URL}" \
    DATABASE_USER="${DATABASE_USER}" \
    DATABASE_PASSWORD="${DATABASE_PASSWORD}" \
    CINCO_CLOUD_DEBUG=${CINCO_CLOUD_DEBUG} \
    CINCO_CLOUD_HOST="${CINCO_CLOUD_HOST}" \
    CINCO_CLOUD_PORT="${CINCO_CLOUD_PORT}" \
    THEIA_WEBVIEW_EXTERNAL_ENDPOINT='{{hostname}}' \
    PYRO_HOST="${PYRO_HOST}" \
    yarn run theia start --port=3000 --root-dir=/editor/workspace --plugins=local-dir:./plugins --hostname 0.0.0.0