apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cinco-cloud
deploy:
  helm:
    releases:
      - name: release
        artifactOverrides:
          mainImage: registry.gitlab.com/scce/cinco-cloud/main
          registryImage: registry.gitlab.com/scce/cinco-cloud/registry
          workspaceBuilderImage: registry.gitlab.com/scce/cinco-cloud/workspace-builder
        chartPath: ./infrastructure/helm
        valuesFiles:
          - ./infrastructure/helm/values.yaml

build:
  tagPolicy:
    gitCommit: { }
  local:
    useBuildkit: true
  artifacts:
    - image: registry.gitlab.com/scce/cinco-cloud/main
      context: ./services
      docker:
        dockerfile: ./main/Dockerfile
      sync:
        infer:
          - '**/*.{ts,html,scss,css,png,jpg,jpeg}'
    - image: registry.gitlab.com/scce/cinco-cloud/registry
      context: ./services/registry
      docker:
        dockerfile: Dockerfile
    - image: registry.gitlab.com/scce/cinco-cloud/workspace-builder
      context: ./services
      docker:
        dockerfile: ./workspace-builder/Dockerfile

profiles:
  - name: local-dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: ./main/dev.Dockerfile
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-local-dev.yaml
  - name: local-prod
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-local-prod.yaml
  - name: local-prod-ssl
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-local-prod-ssl.yaml
  - name: ls5vs024
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-ls5vs024.yaml
  - name: temp
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-temp.yaml
