apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cinco-cloud
deploy:
  helm:
    releases:
      - name: release
        artifactOverrides:
          mainImage: registry.gitlab.com/scce/cinco-cloud/main
          workspaceBuilderImage: registry.gitlab.com/scce/cinco-cloud/workspace-builder
          archetypeImage: registry.gitlab.com/scce/cinco-cloud/archetype
        chartPath: ./infrastructure/helm
        valuesFiles:
          - ./infrastructure/helm/values.yaml

build:
  tagPolicy:
    customTemplate:
      template: "local"
  local:
    useBuildkit: true
  artifacts:
    - image: registry.gitlab.com/scce/cinco-cloud/main
      context: ./cinco-cloud/services
      docker:
        dockerfile: ./main/Dockerfile
      sync:
        infer:
          - '**/*.{ts,html,scss,css,png,jpg,jpeg}'
    - image: registry.gitlab.com/scce/cinco-cloud/workspace-builder
      context: ./cinco-cloud/services
      docker:
        dockerfile: ./workspace-builder/Dockerfile
    - image: registry.gitlab.com/scce/cinco-cloud/archetype
      context: .
      docker:
        dockerfile: ./cinco-cloud-archetype/Dockerfile

profiles:
  - name: local-dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: ./main/dev.Dockerfile
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-local-dev.yaml
  - name: arm
    patches:
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: ./workspace-builder/arm.Dockerfile
  - name: local-prod
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-local-prod.yaml
  - name: demo-k8s-ls5
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-demo-k8s-ls5.yaml
  - name: temp
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-temp.yaml
