apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cinco-cloud
deploy:
  helm:
    releases:
      - name: release
        artifactOverrides:
          mainImage: registry.gitlab.com/scce/cinco-cloud/main
          registryImage: registry.gitlab.com/scce/cinco-cloud/registry
          workspaceBuilderImage: registry.gitlab.com/scce/cinco-cloud/workspace-builder
        chartPath: ./infrastructure/helm
        valuesFiles:
          - ./infrastructure/helm/values.yaml
          - ./infrastructure/helm/values-local.yaml
build:
  tagPolicy:
    gitCommit: { }
  artifacts:
    - image: registry.gitlab.com/scce/cinco-cloud/main
      context: ./main
      docker:
        dockerfile: Dockerfile
    - image: registry.gitlab.com/scce/cinco-cloud/registry
      context: ./registry
      docker:
        dockerfile: Dockerfile
    - image: registry.gitlab.com/scce/cinco-cloud/workspace-builder
      context: .
      docker:
        dockerfile: ./workspace-builder/Dockerfile

profiles:
  - name: temp
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/1
        value: ./infrastructure/helm/values-temp.yaml