apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cinco-cloud
deploy:
  kubectl:
    manifests:
      - .infrastructure/ingress.yaml
      - .infrastructure/ampq.yaml
      - .infrastructure/main.yaml
      - .infrastructure/postgres.yaml
build:
  artifacts:
    - image: registry.gitlab.com/scce/cinco-cloud/main
      context: ./main
      docker:
        dockerfile: Dockerfile