/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.productdefinition.ide;

import org.eclipse.xtext.ide.server.ILanguageServerExtension;

import de.jabc.cinco.meta.productdefinition.ide.endpoint.CincoLanguageServerExtension;

/**
 * Use this class to register ide components.
 */
public class CPDIdeModule extends AbstractCPDIdeModule {

	/**
	 * registering the LanguageServerExtension
	 * @return the LanguageServerExtension including the implemented EndPoints
	 */
	public Class<? extends ILanguageServerExtension> bindILanguageServerExtension() {
		return CincoLanguageServerExtension.class;
	}
}
