/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.productdefinition.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.jabc.cinco.meta.productdefinition.CPDRuntimeModule;
import de.jabc.cinco.meta.productdefinition.CPDStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CPDIdeSetup extends CPDStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CPDRuntimeModule(), new CPDIdeModule()));
	}
	
}
