apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ampq-statefulset
  labels:
    app: ampq
spec:
  serviceName: ampq
  replicas: 1
  selector:
    matchLabels:
      app: ampq
  template:
    metadata:
      labels:
        app: ampq
    spec:
      containers:
        - name: ampq
          image: {{ .Values.ampqImage }}
          env:
            - name: AMPQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cinco-cloud-main-secrets
                  key: artemisUser
            - name: AMPQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cinco-cloud-main-secrets
                  key: artemisPassword
          ports:
            - containerPort: 5672
            - containerPort: 61616
            - containerPort: 8161
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: ampq-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: ampq-service
  labels:
    app: ampq
spec:
  ports:
    - port: 5672
      name: ampq
      protocol: TCP
    - port: 61616
      name: ampq-core
      protocol: TCP
    - port: 8161
      name: ampq-server
  {{ if or (eq .Values.serverTier "local") (eq .Values.serverTier "local-ssl") }}
  type: NodePort
  {{- else -}}
  type: ClusterIP
  {{- end }}
  selector:
    app: ampq
---
{{ if eq .Values.createPersistentVolumes true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ampq-pv-volume
  labels:
    type: local
    app: ampq
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.artemis.storage | default "2Gi" | quote }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: ampq-pv-claim
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.artemis.hostPath }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ampq-pv-claim
  labels:
    app: ampq
spec:
  storageClassName: {{ .Values.storageClassName }}
  {{ if eq .Values.createPersistentVolumes true }}
  volumeName: ampq-pv-volume
  {{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.artemis.storage | default "2Gi" | quote }}