apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-statefulset
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2023-11-01T18-37-25Z
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: cinco-cloud-main-secrets
                  key: minioRootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cinco-cloud-main-secrets
                  key: minioRootAdmin
          ports:
            - containerPort: 9000
            - containerPort: 9001
          resources:
            limits:
              cpu: {{ .Values.minio.cpu | default "1000m" | quote }}
              memory: {{ .Values.minio.memory | default "2Gi" | quote }}
          volumeMounts:
            - mountPath: /data
              name: pv-data
          command: ["/bin/sh","-c"]
          args: ["minio server /data --console-address ':9001'"]
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: minio-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio
spec:
  ports:
    - port: 9000
      name: minio-frontend
      protocol: TCP
    - port: 9001
      name: minio-backend
      protocol: TCP
  type: NodePort
  selector:
    app: minio
---
{{ if eq .Values.createPersistentVolumes true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume
  labels:
    type: local
    app: minio
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.minio.storage | default "10Gi" | quote }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: minio-pv-claim
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.minio.hostPath }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio
spec:
  storageClassName: {{ .Values.storageClassName }}
  {{ if eq .Values.createPersistentVolumes true }}
  volumeName: minio-pv-volume
  {{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.minio.storage | default "10Gi" | quote }}
