apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-builder-config
  namespace: {{ .Values.namespace }}
data:
  AMPQ_HOST: "ampq-service"
  AMPQ_PORT: "5672"
  MINIO_HOST: "minio-service"
  MINIO_PORT: "9000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-builder-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: workspace-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace-builder
  template:
    metadata:
      labels:
        app: workspace-builder
    spec:
      containers:
        - name: workspace-builder
          image: {{ .Values.workspaceBuilderImage }}
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: workspace-builder-config
          env:
            - name: AMPQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cinco-cloud-main-secrets
                  key: artemisUser
            - name: AMPQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cinco-cloud-main-secrets
                  key: artemisPassword
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cinco-cloud-main-secrets
                  key: minioAccessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cinco-cloud-main-secrets
                  key: minioSecretKey
          securityContext:
            privileged: true
      imagePullSecrets:
        - name: {{ .Values.registries.cincocloud.secret.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-builder-service
  namespace: {{ .Values.namespace }}
  labels:
    app: workspace-builder
spec:
  ports:
    - port: 8000
      name: main
      protocol: TCP
  {{ if eq .Values.serverTier "local" }}
  type: NodePort
  {{- else -}}
  type: ClusterIP
  {{- end }}
  selector:
    app: workspace-builder
