/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.core.ge.style;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StyleRuntimeModule extends AbstractStyleRuntimeModule {
}
