/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.core.ge.style;

import org.eclipse.emf.ecore.EPackage;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StyleStandaloneSetup extends StyleStandaloneSetupGenerated {

	public static void doSetup() {
		new StyleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		// Registering EPackages
		if (!EPackage.Registry.INSTANCE.containsKey(style.StylePackage.eNS_URI+"#//Style")) {
			EPackage.Registry.INSTANCE.put(style.StylePackage.eNS_URI+"#//Style", style.StylePackage.eINSTANCE);
		}
		super.register(injector);
	}
}
