apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: default
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiYWJhaW5jenlrIiwicGFzc3dvcmQiOiJNN3NyZHZCc1JwNUZzcnhkeXNadCIsImVtYWlsIjoiYWxleGFuZGVyLmJhaW5jenlrQHR1LWRvcnRtdW5kLmRlIiwiYXV0aCI6IllXSmhhVzVqZW5sck9rMDNjM0prZGtKelVuQTFSbk55ZUdSNWMxcDAifX19
type: kubernetes.io/dockerconfigjson