/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.productdefinition.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import productDefinition.CincoProduct

@ExtendWith(InjectionExtension)
//@InjectWith(CPDInjectorProvider)
class CPDParsingTest {
	//@Inject
	//ParseHelper<CincoProduct> parseHelper
	
	@Test
	def void loadModel() {
		/*
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		*/
	}
}
/* SAMI: This test does not work, since this package, needs to inject a workspace-root-path, received from the ide context.
 * Thus, there needs to be a Fallback way, to let this package work as standalone or the test create such workspace-root-path.
 */