version: "3.2"
networks:
  postgres:
  nginx:
volumes:
  maven_cache:
  pub_cache:
services:
  nginx:
    depends_on:
      - angular
      - quarkus
    image: nginx:1.18
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - nginx
    ports:
      - "8080:80"
  angular:
    image: google/dart:2.4.1
    networks:
      - nginx
    volumes:
      - "pub_cache:/root/.pub-cache"
      - "./webapp/lib:/usr/src/app/lib:ro"
      - "./webapp/web:/usr/src/app/web:ro"
      - "./webapp/pubspec.yaml:/usr/src/app/pubspec.yaml:ro"
    working_dir: /usr/src/app
    entrypoint: sh -c "pub get && pub run build_runner serve --hostname=0.0.0.0" // sh -c "pub get && pub global activate webdev && /root/.pub-cache/bin/webdev serve --hostname=0.0.0.0"
    ports:
      - "9100:9100"
  quarkus:
    depends_on:
      - postgres
    networks:
      - postgres
      - nginx
    image: openjdk:15-jdk-alpine3.11
    volumes:
      - "maven_cache:/root/.m2"
      - "./app/src:/usr/src/server/src:ro"
      - "./app/.classpath:/usr/src/server/.classpath:ro"
      - "./app/mvnw:/usr/src/server/mvnw:ro"
      - "./app/pom.xml:/usr/src/server/pom.xml:ro"
      - "./app/.mvn:/usr/src/server/.mvn:ro"
    working_dir: /usr/src/server
    entrypoint: ./mvnw
    command: compile quarkus:dev -Ddebug
  postgres:
    environment:
      POSTGRES_DB: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_USER: quarkus_test
    image: postgres:11.2
    networks:
      - postgres
