/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.core.mgl;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EcorePackage;
import org.eclipse.emf.ecore.plugin.EcorePlugin;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl;
import org.eclipse.emf.ecore.xmi.impl.EcoreResourceFactoryImpl;

import com.google.inject.Injector;

import graphmodel.GraphmodelPackage;
import mgl.MglPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MGLStandaloneSetup extends MGLStandaloneSetupGenerated {

	public static void doSetup() {
		new MGLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		// Registering EPackages
		if (!EPackage.Registry.INSTANCE.containsKey(EcorePackage.eNS_URI)) {
			EPackage.Registry.INSTANCE.put(EcorePackage.eNS_URI, EcorePackage.eINSTANCE);
		}
		if (!EPackage.Registry.INSTANCE.containsKey(GraphmodelPackage.eNS_URI)) {
			EPackage.Registry.INSTANCE.put(GraphmodelPackage.eNS_URI, GraphmodelPackage.eINSTANCE);
		}
		if (!EPackage.Registry.INSTANCE.containsKey(MglPackage.eNS_URI)) {
			EPackage.Registry.INSTANCE.put(MglPackage.eNS_URI, mgl.MglPackage.eINSTANCE);
		}
		
		org.eclipse.xtext.resource.IResourceFactory resourceFactory = injector.getInstance(org.eclipse.xtext.resource.IResourceFactory.class);
	    org.eclipse.xtext.resource.IResourceServiceProvider serviceProvider = injector.getInstance(org.eclipse.xtext.resource.IResourceServiceProvider.class);
	    Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put(EcorePackage.eNAME, resourceFactory);
	    org.eclipse.xtext.resource.IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put(EcorePackage.eNAME, serviceProvider);
		
		super.register(injector);
	}
}
