/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.core.mgl;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MGLStandaloneSetup extends MGLStandaloneSetupGenerated {

	public static void doSetup() {
		new MGLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		// Registering EPackages
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.jabc.de/cinco/meta/core/mgl#//GraphModel")) {
			EPackage.Registry.INSTANCE.put("http://www.jabc.de/cinco/meta/core/mgl#//GraphModel", graphmodel.GraphmodelPackage.eINSTANCE);
		}
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.jabc.de/cinco/meta/core/mgl#//MGL")) {
			EPackage.Registry.INSTANCE.put("http://www.jabc.de/cinco/meta/core/mgl#//MGL", mgl.MglPackage.eINSTANCE);
		}
		super.register(injector);
	}
}
