import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { MslGeneratedModule, CincoGeneratedSharedModule } from '../../generated/module';
import { MslValidator, registerValidationChecks } from './msl-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MslAddedServices = {
    validation: {
        MslValidator: MslValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MslServices = LangiumServices & MslAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MslModule: Module<MslServices, PartialLangiumServices & MslAddedServices> = {
    validation: {
        MslValidator: () => new MslValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMslServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Msl: MslServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        CincoGeneratedSharedModule
    );
    const Msl = inject(
        createDefaultModule({ shared }),
        MslGeneratedModule,
        MslModule
    );
    shared.ServiceRegistry.register(Msl);
    registerValidationChecks(Msl);
    return { shared, Msl };
}
