{{- if eq .Values.serverTier "local-ssl" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cinco-cloud-local-development-cert
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Values.ingress.host }}
  dnsNames:
    - {{ .Values.ingress.host }}
  subject:
    organizations:
      - Cinco Cloud Local Development Org.
  secretName: cinco-cloud-local-ca-cert-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
{{- end }}
