import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { MglGeneratedModule, CincoGeneratedSharedModule } from '../../generated/module';
import { MglValidator, registerValidationChecks } from './mgl-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MglAddedServices = {
    validation: {
        MglValidator: MglValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MglServices = LangiumServices & MglAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MglModule: Module<MglServices, PartialLangiumServices & MglAddedServices> = {
    validation: {
        MglValidator: () => new MglValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMglServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Mgl: MglServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        CincoGeneratedSharedModule
    );
    const Mgl = inject(
        createDefaultModule({ shared }),
        MglGeneratedModule,
        MglModule
    );
    shared.ServiceRegistry.register(Mgl);
    registerValidationChecks(Mgl);
    return { shared, Mgl };
}
