/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.core.mgl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.jabc.cinco.meta.core.mgl.MGLRuntimeModule;
import de.jabc.cinco.meta.core.mgl.MGLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MGLIdeSetup extends MGLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MGLRuntimeModule(), new MGLIdeModule()));
	}
	
}
