/*
 * generated by Xtext 2.22.0
 */
package de.jabc.cinco.meta.productdefinition;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CPDStandaloneSetup extends CPDStandaloneSetupGenerated {

	public static void doSetup() {
		new CPDStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.jabc.de/cinco/meta/productdefinition#//CPD")) {
			EPackage.Registry.INSTANCE.put("http://www.jabc.de/cinco/meta/productdefinition#//CPD", productDefinition.ProductDefinitionPackage .eINSTANCE);
		}
		super.register(injector);
	}
}
